openapi: 3.0.3
info:
  version: 1.0.0
  title: formekou-api
  description: Api that can manage forms
security:
  - BearerAuth: []
paths:
  '/dummy-table':
    get:
      tags:
        - Health
      summary: Get all dummies
      operationId: getDummies
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dummy'
        '400':
          $ref: '#/components/responses/BadRequest'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/ping':
    get:
      tags:
        - Health
      summary: Pong
      operationId: ping
      responses:
        '200':
          description: Pong
          content:
            text/plain:
              schema:
                type: string
                example: pong
        '400':
          $ref: '#/components/responses/BadRequest'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/whoami':
    get:
      tags:
        - Security
      summary: Tell who you are using firebase token
      operationId: getWhoAmi
      responses:
        '200':
          description: Who you are
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          $ref: '#/components/responses/BadRequest'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  '/signup':
    post:
      tags:
        - Security
      summary: create a account using email, lastName and password
      operationId: doSignup
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUser'
      responses:
        '200':
          description: Register a new user account.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          $ref: '#/components/responses/BadRequest'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  schemas:
    Dummy:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
    User:
      properties:
        id:
          type: string
          format: uuid
        firstName:
          type: string
          example: mioratiana
        lastName:
          type: string
          example: TSANTANIAINA
        email:
          type: string
          example: hei.tsantaniaina@gmail.com
    CreateUser:
      allOf:
        - $ref: '#/components/schemas/User'
      properties:
        password:
          type: string
  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          example:
            error: "Invalid request parameters"
    Forbidden:
      description: Forbidden
      content:
        application/json:
          example:
            error: "Access forbidden"
    NotFound:
      description: Not Found
      content:
        application/json:
          example:
            error: "Resource not found"
    TooManyRequests:
      description: Too Many Requests
      content:
        application/json:
          example:
            error: "Too many requests, please try again later"
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          example:
            error: "Internal server error occurred"