name: Publish DB 

on:
  push:
    branches: ["prod"]
  workflow_dispatch:

jobs:
  run-migrations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Execute publish_db.sh
        run: |
          chmod +x publish_db.sh
          ./publish_db.sh ${{ secrets.DB_USERNAME }} \
                         ${{ secrets.DB_PASSWORD }} \
                         ${{ secrets.DB_HOST }} \
                         ${{ secrets.DB_PORT }} \
                         ${{ secrets.DB_NAME }} \
                         ${{ secrets.MIGRATION_PATH }}
